### ISSUE TITLE
question: use of relaton autofetch for IEV within metanorma/ieee template

### ISSUE THREAD

**Issue by ReesePlews** [relaton/relaton-iev#22]
i have a question regarding the use of relaton autofetch for a reference to the IEV.

i am using that both in clause 3 and also in the bibliography. this work takes place on github (asciidoc) using 

> Metanorma 1.6.7
> Metanorma::Cli 1.8.9
> Metanorma::Standoc 2.7.0/IsoDoc 2.7.1
> Metanorma::ISO 2.6.0
> Metanorma::Iec 2.3.5
> Metanorma::IEEE 1.1.7

i have looked at some closed issues that highlighted discussions here and also checked the documentation but i am still having some difficulty to get the render correct.

the images and code below show some of the issues

> 
> * [[[iev,IEC Electropedia]]],
> 
> * [[[ievtermbank,IEC Electropedia]]],
> 
> * [[[ievterms,IEV]]]

render as

![image](https://github.com/relaton/relaton-iev/assets/35089343/a83f3c51-1835-4ef6-9890-195f4cd0e929)

i am not sure which one is not rendering

i am also trying to use this in clause3  as

>  [.source]
> <<ievterms,clause=02-03-19>>, Note 1 has been modified. Note 2 has been added.

which renders as (no matter which form i use)

![image](https://github.com/relaton/relaton-iev/assets/35089343/0e8e2624-1365-4fa9-b8b6-e29e9124c03b)

if you could point me to the current documentation on this function or tell me which form i should use that would be very helpful.  this is not a priority at this time. thank you.

**Comment by ReesePlews** [comment]
additionally, when relaton is fetching entries for a bibliography, as shown below...

> [relaton-iec] (IEC Electropedia) Fetching from Relaton repsitory ...
> [relaton-iec] (IEC Electropedia) Not found.

is there a way to turn on output to show what i am asking (sending) to relaton to fetch?

after the word "Fetching from Relaton repository ..."  could that be modified to show:
"Fetching [ievterms] from Relaton repository..."  so when an error is encountered it would show which entry is causing the error?

**Comment by opoudjis** [comment]
https://www.metanorma.org/author/topics/document-format/section-terms/#sourcing-concepts-from-termbases

Only `* [[[ievterms,IEV]]]` will work. We have not defined "IEC Electropedia" as a synonym of IEC 60050, only "IEV".

`<<ievterms,clause=02-03-19>>` is almost certainly wrong: it implies that the term is defined in IEC 60050-02.

Euclidean space is https://www.electropedia.org/iev/iev.nsf/display?openform&ievref=102-03-19 : 102-03-19. So, `<<ievterms,clause=102-03-19>>`.

The error message is completely correct: what you were trying to fetch WAS "IEC Electropedia", and that reference is not recognised at all, which is what the error message is telling you.
