### ISSUE TITLE
Do not generate "*.pstore" files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iev#5]
The IEV cache should not store `pstore` files, just like the Relaton gems no longer store them.

**Comment by andrew2net** [comment]
@ronaldtse where do you see `*.pstore` files? I can't find such files.

**Comment by ronaldtse** [comment]
If you clone https://github.com/CalConnect/csd-admin-documents , run `make all`, you can see the `iev.pstore` directories created.

**Comment by andrew2net** [comment]
@ronaldtse did it but still don't see any `*.pstore` files or directories. Maybe they remain form the old version? Did you try do delete them?

**Comment by ronaldtse** [comment]
Not showing anymore, closing.
